import operator
from typing import Annotated, TypedDict


def _merge_dicts(a: dict, b: dict) -> dict:
    """Reducer: merges dict updates rather than replacing the entire dict."""
    return {**a, **b}


class PRDState(TypedDict):
    # ── Session identity ─────────────────────────────────────────────────────
    thread_id: str   # stable session identifier (set once per Streamlit session)
    run_id: str      # one graph invocation — UUID generated per .invoke() call

    # ── Static configuration ─────────────────────────────────────────────────
    context_doc: str        # raw text of the optional uploaded document (kept for compat)
    max_iterations: int     # max reflection loops per section (default: 3)

    # ── Session phase (D-M12) ─────────────────────────────────────────────────
    # "discovery"   — probing PATH_2/3 users before PRD work starts (max 3 turns)
    # "elicitation" — normal PRD section Q&A
    phase: str
    framing_mode: str       # "clear" | "symptom_only" | "confused" — set by detect_framing
    discovery_turn_count: int  # number of discovery turns used; does not count against iteration

    # ── Section navigation ────────────────────────────────────────────────────
    section_index: int      # index into PRD_SECTIONS list
    iteration: int          # current reflection iteration for this section

    # ── Current section workflow ──────────────────────────────────────────────
    current_questions: str  # questions generated by Elicitor
    current_draft: str      # draft produced by Drafter
    verdict: str            # "PASS" | "REWORK" | ""
    triage_decision: str    # "TRIAGE: ENTER RECOVERY MODE" | "TRIAGE: NORMAL ITERATION"
    recovery_mode_consecutive_count: int  # consecutive ENTER RECOVERY MODE verdicts
    overall_score: float    # parsed OVERALL SCORE from reflector (-1.0 = not parsed)

    # ── Reflector outputs (v2: JSON schema) ───────────────────────────────────
    # technical_gaps: internal only — fed to Elicitor for follow-up questions
    # user_gaps:      plain English — shown to user in feedback panel
    # reflection:     raw reflector JSON string (kept for logging/debug)
    reflection: str
    technical_gaps: str     # internal, never shown to user
    user_gaps: str          # plain English, shown to user
    requirement_gaps: str   # DEPRECATED: kept for backward compat during migration

    # ── Confirmed answers store (D-M5) ────────────────────────────────────────
    # Source of truth for all confirmed user answers.
    # Keys are canonical concept keys (e.g. "team_size", "problem_statement").
    # Each value: {"answer": str, "section": str, "contradiction_flagged": bool}
    # Uses merge reducer so individual concepts can be updated without full replace.
    confirmed_qa_store: Annotated[dict, _merge_dicts]

    # ── section_qa_pairs (DEPRECATED as source of truth) ─────────────────────
    # Kept as a derived view written simultaneously with confirmed_qa_store.
    # Reflector reads this for backward compat until Reflector is fully migrated.
    # Format: [{"questions": str, "answer": str, "section": str}]
    section_qa_pairs: list

    # ── Interrupt routing (D-M6) ──────────────────────────────────────────────
    # Set before every interrupt(). Routing edge reads on resume to dispatch correctly.
    # "question"     — user answering an Elicitor question
    # "bounds_check" — user confirming an implausible number (rule-based, no LLM)
    # ""             — no interrupt pending
    pending_interrupt_type: str
    # Queue for secondary interrupts when two triggers fire on the same answer.
    # Each item: {"type": str, "payload": dict}
    interrupt_queue: list

    # ── Image context (D-M3) ─────────────────────────────────────────────────
    # Gemini Vision text descriptions of uploaded images.
    # Injected into Elicitor context block when non-empty.
    # Capped at 3 most recent descriptions at injection time.
    image_context: Annotated[list, operator.add]

    # ── Forward hints (D-M13) ────────────────────────────────────────────────
    # User-volunteered facts about future PRD sections captured early.
    # Surfaced as confirmation reminders when that section is reached.
    # NOT written to confirmed_qa_store until user re-confirms in context.
    # Each item: {"section_id": str, "hint": str}
    forward_hints: Annotated[list, operator.add]

    # ── Contradiction log (O-1b) ──────────────────────────────────────────────
    # Observability log of detected contradictions this session.
    # Each item: {"concept_key": str, "prior": str, "new": str, "section": str}
    # Used to append reviewer note to final PRD if any contradiction_flagged remain.
    contradiction_log: Annotated[list, operator.add]

    # ── TBD fields (D-M12 zero-context fallback) ─────────────────────────────
    # Concept keys that could not be captured (user consistently unable to answer).
    # Flagged in final PRD reviewer note.
    tbd_fields: list

    # ── Accumulated PRD content ───────────────────────────────────────────────
    # Uses merge reducer so nodes can write one section at a time.
    prd_sections: Annotated[dict, _merge_dicts]

    # ── UI chat history (append-only) ─────────────────────────────────────────
    # Display only — never used as source of truth for answer content.
    # Each item: {"role": str, "type": str, "content": str, ...extra}
    chat_history: Annotated[list, operator.add]

    # ── Reflector confidence (Step 6 D-M8 JSON output) ──────────────────────
    confidence: float    # 0.0–1.0 from JSON block; -1.0 = not parsed

    # ── Provisional answer state (confirmation gate) ───────────────────────
    # Answers are provisional until explicitly confirmed by the user.
    # confirmed_qa_store must only receive CONFIRMED values.
    raw_answer_buffer: str       # latest unconfirmed raw user response
    pending_echo: str            # system restatement awaiting user confirmation
    pending_concept_updates: dict  # candidate Q&A not yet promoted to canonical truth
    answer_confirmation_status: str  # "" | "PENDING" | "CONFIRMED" | "CORRECTED"

    # ── Structured event payload (message tagging, D-M14) ─────────────────
    # Set by await_answer_node when user submits a structured tagged event.
    # Cleared by handle_tagged_event_node or interpret_and_echo_node.
    # Fields: {event_type, content, target_message_id, target_content, ...optional}
    pending_event: dict

    # ── Event history (provenance log) ────────────────────────────────────
    # Append-only log of processed TAG_MESSAGE_AS_TRUTH and CORRECT_MESSAGE events.
    # Each item: {event_type, target_message_id, content, section, concept_key}
    event_history: Annotated[list, operator.add]

    # ── Hybrid opportunistic updater (Phase 1) ────────────────────────────
    # section_scores: per-section completeness/confidence written by reflect_node.
    #   {section_id: {"completeness": float, "confidence": float, "verdict": str}}
    #   Uses merge reducer so individual sections can be updated independently.
    section_scores: Annotated[dict, _merge_dicts]

    # ── Draft output cache (performance optimization) ─────────────────────
    # Keyed {section_id: {cache_key_hash: draft_text}}.
    # Cache key is SHA-256 of section-relevant Q&A + dependency-scoped PRD context.
    # Only the latest key per section is retained to keep size bounded.
    draft_cache: Annotated[dict, _merge_dicts]

    # Section-level draft policy state.
    # {section_id: {
    #   "facts": list[str],
    #   "confidence_score": float,
    #   "completeness_score": float,
    #   "last_draft_hash": str,
    #   "state": str,
    #   ...internal bookkeeping
    # }}
    section_draft_meta: Annotated[dict, _merge_dicts]

    # Result of the most recent draft node for routing.
    # "drafted" → continue to reflect, "skipped" → go back to question generation.
    draft_execution_mode: str

    # Impact confidence scores set by detect_impact_node.
    # {section_id: float} — 1.0 = rule-based, 0.7 = LLM-fallback, 0.4 = side-fact.
    # Side-writes below _SIDE_WRITE_MIN_IMPACT_SCORE are skipped in draft_node.
    impacted_section_scores: Annotated[dict, _merge_dicts]

    # Memoised formatted PRD context — avoids re-serialising prd_sections each node.
    _prd_sections_fmt_hash: str   # sha256 of prd_sections used in last format call
    _formatted_prd_so_far: str    # last output of _format_prd_so_far

    # impacted_sections: set by detect_impact_node each turn.
    #   List of already-drafted section IDs that should be re-drafted this turn
    #   (excludes current section; capped at MAX_SIDE_WRITES=2).
    impacted_sections: list

    # last_section_updates: section IDs written in the most recent draft_node call.
    #   Overwritten each turn (not append-reduced). Used by UI for badges.
    last_section_updates: list

    # ── Final output ──────────────────────────────────────────────────────────
    prd_markdown: str
    is_complete: bool
