import operator
from typing import Annotated, TypedDict


def _merge_dicts(a: dict, b: dict) -> dict:
    """Reducer: merges dict updates rather than replacing the entire dict."""
    return {**a, **b}


class PRDState(TypedDict):
    # ── Session identity (used to scope log files) ──────────────────────────
    thread_id: str   # stable session identifier (set once per Streamlit session)
    run_id: str      # one graph invocation — UUID generated per .invoke() call

    # ── Static configuration ────────────────────────────────────────────────
    context_doc: str        # raw text of the optional uploaded document
    max_iterations: int     # max reflection loops per section (default: 3)

    # ── Section navigation ──────────────────────────────────────────────────
    section_index: int      # index into PRD_SECTIONS list
    iteration: int          # current reflection iteration for this section

    # ── Current section workflow ────────────────────────────────────────────
    current_questions: str                  # questions generated by Elicitor
    section_qa_pairs: list                  # [{"questions": str, "answer": str}]
    current_draft: str                      # draft produced by Drafter
    reflection: str                         # full reflection text from Reflector
    verdict: str                            # "PASS" | "REWORK" | ""
    requirement_gaps: str                   # extracted REQUIREMENT GAPS block from reflection
    triage_decision: str                    # "TRIAGE: ENTER RECOVERY MODE" | "TRIAGE: NORMAL ITERATION"
    recovery_mode_consecutive_count: int    # consecutive ENTER RECOVERY MODE verdicts
    overall_score: float                    # parsed OVERALL SCORE from reflector (-1.0 = not parsed)

    # ── Accumulated PRD content ─────────────────────────────────────────────
    # Uses merge reducer so nodes can write one section at a time
    prd_sections: Annotated[dict, _merge_dicts]

    # ── UI chat history (append-only) ───────────────────────────────────────
    # Each item: {"role": str, "type": str, "content": str, ...extra}
    chat_history: Annotated[list, operator.add]

    # ── Final output ────────────────────────────────────────────────────────
    prd_markdown: str
    is_complete: bool
